### ISSUE TITLE
Share build steps for custom fly premrna reference

### ISSUE THREAD

**Issue by liuyifang** [FlyCellAtlas/genome_references#1]
Hi,

Thanks for providing dmel-all-r6.31-premrna.gtf.gz. Could you share the scripts about how you build the reference similar to 10x below? Thanks!

![image](https://user-images.githubusercontent.com/520808/74277044-d9e2df00-4ce4-11ea-8baa-b733e7572af1.png)

**Comment by dweemx** [comment]
Hi @liuyifang.

Sorry for my very late response :/ I was quite busy with some other stuff
Anyway I compiled a recipe [here](https://github.com/FlyCellAtlas/genome_references/tree/master/flybase/r6.31)
